### ISSUE TITLE
Missing additional Google Cloud mappings

### ISSUE THREAD

**Issue by crcsmnky** [ilyas-it83/CloudComparer#12]
The following mappings are missing/outdated from the comparison tool:

* Compute/App Development: [App Engine](https://cloud.google.com/appengine/)
* Storage/Long Term Cold Storage: [Cloud Storage Nearline](https://cloud.google.com/storage/archival/) and [Cloud Storage Coldline](https://cloud.google.com/storage/archival/)
* Migration Services/Server Migration Services: [Google Cloud VM Migration](https://cloud.google.com/migrate/)
* Management Tools/Cloud Deployment Templates/ Infra as Code: [Cloud Deployment Manager](https://cloud.google.com/deployment-manager/)
* Management Toosl/Resource/Configuration Inventory: [Cloud Resource Manager](https://cloud.google.com/resource-manager/)
* Security/Cloud Security Assesment Service: [Cloud Security Scanner](https://cloud.google.com/security-scanner/)
* Security/Key Management Services: [Cloud Key Management Service](https://cloud.google.com/kms/)
* Security/Consolidated Manag of Multiple Cloud Accounts: [Cloud Resource Manager](https://cloud.google.com/resource-manager/)
* Security/DDos Protection Service: [Cloud Security Design](https://cloud.google.com/security/security-design/#denial_of_service_dos_protection)
* Big Data/Big Data Query as a Service: [BigQuery](https://cloud.google.com/bigquery)
* Software Marketplace/Cloud Marketplace: [Cloud Launcher](https://cloud.google.com/launcher)
* IoT/Hardware: [Cloud IoT Kit](https://cloud.google.com/solutions/iot/kit/)

**Comment by ilyas-it83** [comment]
Hi @crcsmnky, Thanks for the input, will review and update the comparison shortly.

Thanks
Ilyas

**Comment by ilyas-it83** [comment]
Compute/App Development: App Engine - Added
Storage/Long Term Cold Storage: Cloud Storage Nearline and Cloud Storage Coldline - Added
Migration Services/Server Migration Services: Google Cloud VM Migration - Doesnt qualify, because it has to be a full fledged managed cloud service offering 
Management Tools/Cloud Deployment Templates/ Infra as Code: Cloud Deployment Manager - Added
Management Toosl/Resource/Configuration Inventory: Cloud Resource Manager - Added
Security/Cloud Security Assesment Service: Cloud Security Scanner - Added
Security/Key Management Services: Cloud Key Management Service - Added
Security/Consolidated Manag of Multiple Cloud Accounts: Cloud Resource Manager - Added
Security/DDos Protection Service: Cloud Security Design - Doesnt qualify, because it has to be a full fledged managed cloud service offering.
Big Data/Big Data Query as a Service: BigQuery - Added
Software Marketplace/Cloud Marketplace: Cloud Launcher - Added
IoT/Hardware: Cloud IoT Kit - Added
