### ISSUE TITLE
Email Services

### ISSUE THREAD

**Issue by kylecweeks** [ilyas-it83/CloudComparer#47]
How is Microsoft Exchange Online not listed as Email Services?

Exchange Online is directly integrated into an Azure AD Tenant space, and relies entirely upon Azure to function.

**Comment by ilyas-it83** [comment]
Grt, but its a standalone SaaS Offering and hence it doesn't qualify as a managed cloud service offering. Good example is SES on AWS, its an email service that developers can use and send email right from their app. Azure doesnt provide something similar and positions sendgrid as an alternate. Closing the issue for now, please open if you thin otherwise.
